// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCopftMc5Belvzrym86hheLDc0fZJtMZ6s',
    appId: '1:1034974394954:web:877c68e9f7faf2b11904b3',
    messagingSenderId: '1034974394954',
    projectId: 'reservation-system-961',
    authDomain: 'reservation-system-961-2649b.firebaseapp.com',
    databaseURL: 'https://reservation-system-961-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'reservation-system-961.appspot.com',
    measurementId: 'G-E6P35NZ9P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBclySPvtkOYdsd0Zwyz1pY-jrbqbI_4',
    appId: '1:1034974394954:android:03f3ee151c183c6c1904b3',
    messagingSenderId: '1034974394954',
    projectId: 'reservation-system-961',
    databaseURL: 'https://reservation-system-961-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'reservation-system-961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqJzKoEfE6gICb1Q3ycDutN92vPI9ey4',
    appId: '1:1034974394954:ios:dbef51e533da45981904b3',
    messagingSenderId: '1034974394954',
    projectId: 'reservation-system-961',
    databaseURL: 'https://reservation-system-961-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'reservation-system-961.appspot.com',
    iosBundleId: 'com.example.courtify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqJzKoEfE6gICb1Q3ycDutN92vPI9ey4',
    appId: '1:1034974394954:ios:9dd3709c82e7adc31904b3',
    messagingSenderId: '1034974394954',
    projectId: 'reservation-system-961',
    databaseURL: 'https://reservation-system-961-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'reservation-system-961.appspot.com',
    iosBundleId: 'com.example.courtify.RunnerTests',
  );
}
